name: main

on: [push, pull_request]

jobs:
  full-flambda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Packages
      run: |
        sudo apt-get update -y && sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended
  # Ensure that make distclean can be run from an empty tree
    - name: distclean
      run: |
        MAKE_ARG=-j make distclean
    - name: configure tree
      run: |
        MAKE_ARG=-j XARCH=x64 CONFIG_ARG='--enable-flambda --enable-dependency-generation' OCAMLRUNPARAM=b,v=0 bash -xe tools/ci/actions/runner.sh configure
    - name: Build
      run: |
        MAKE_ARG=-j OCAMLRUNPARAM=b,v=0 bash -xe tools/ci/actions/runner.sh build
    - name: Run the testsuite
      run: |
        for i in `seq 1 20`; do OCAMLRUNPARAM=b,v=0 make -C testsuite USE_RUNTIME=d OCAMLTESTDIR="$(pwd)/testsuite/_ocamltestd" TESTLOG=_logd one TEST=tests/misc/ephe_infix.ml; done
        make -s install && ./ocamlopt -runtime-variant d testsuite/tests/misc/ephe_infix.ml -o /tmp/e && /tmp/e
        MAKE_ARG=-j OCAMLRUNPARAM=b,v=0 bash -xe tools/ci/actions/runner.sh test
